# Generated by Django 4.2.1 on 2023-05-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AqiDataDbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_lat', models.IntegerField()),
                ('station_lon', models.IntegerField()),
                ('aqi_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EqDataDbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epi_lat', models.IntegerField()),
                ('epi_lon', models.IntegerField()),
                ('seismic_intensity', models.CharField(max_length=5)),
                ('shaking_area_lat', models.IntegerField()),
                ('shaking_area_lon', models.IntegerField()),
            ],
        ),
    ]
