# Generated by Django 4.2.1 on 2023-05-04 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('display_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqdatadbmodel',
            name='eq_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
