# Generated by Django 4.2.1 on 2023-05-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_info', '0002_eqdatadbmodel_eq_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqdatadbmodel',
            name='eq_time',
            field=models.CharField(max_length=30),
        ),
    ]
