# Generated by Django 4.2.1 on 2023-05-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_info', '0003_alter_eqdatadbmodel_eq_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqidatadbmodel',
            name='station_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='aqidatadbmodel',
            name='station_lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eqdatadbmodel',
            name='epi_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eqdatadbmodel',
            name='epi_lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eqdatadbmodel',
            name='shaking_area_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eqdatadbmodel',
            name='shaking_area_lon',
            field=models.FloatField(),
        ),
    ]
