# Generated by Django 4.2.1 on 2023-05-04 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display_info', '0005_aqidatadbmodel_aqi_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aqidatadbmodel',
            name='aqi_time',
        ),
        migrations.RemoveField(
            model_name='eqdatadbmodel',
            name='seismic_intensity',
        ),
        migrations.RemoveField(
            model_name='eqdatadbmodel',
            name='shaking_area_lat',
        ),
        migrations.RemoveField(
            model_name='eqdatadbmodel',
            name='shaking_area_lon',
        ),
        migrations.CreateModel(
            name='IntensityDbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaking_area_lat', models.FloatField()),
                ('shaking_area_lon', models.FloatField()),
                ('seismic_intensity', models.CharField(max_length=5)),
                ('id_earthquake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display_info.eqdatadbmodel')),
            ],
        ),
    ]
