# Generated by Django 4.2.1 on 2023-05-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_info', '0006_remove_aqidatadbmodel_aqi_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqidatadbmodel',
            name='aqi_time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='eqdatadbmodel',
            name='eq_magnitude',
            field=models.FloatField(default=0),
        ),
    ]
